### ISSUE TITLE
bug on attribute

### ISSUE THREAD

**Issue by rubydesign** [tario/to_erb#1]
Hi, just really wanted to say thanks. 

This little thing (best I found on te net) just converted my old haml project with just one little glitch.

Here it is if you want to work on it . Otherwise close this, because off course I did the trivial conversion by hand

The href is the offending line (maybe not even valid haml anymore for all i know)
# demo.demolayout

```
%ul#demo-nav.demolayout
    %li
        <a class="active" href="/#{@lang}/#tab1">Katso my&ouml;s</a>
.tabs-container
    .tab#tab1(style="display: block;" )
        - show.each do |box|
            = render("part/#{box}") 
        .clear
```

.clear

**Comment by tario** [comment]
I do not understand what exactly the bug is, 
Do you say that html syntax is not properly converted (the link fail to convert?) ?
Can you send me more examples?

NOTE: if you want, fork the project and fix the bug, and I will test and integrate it , i will add you to authors file of course

**Comment by rubydesign** [comment]
Aha, I see that gihub screwed the haml.
I'm sorry, I moved on, all haml is deleted and I have no time to fix this.

The error was inthe href (that github made to a link) , sorry :-)

I actually found that it didn't convert the inline ruby so well (or not working), but also that I fixed.  You can try this by putting ruby into the haml and see if it still works in the converted erb. (didn't for me)

Still, the main message was thanks, so I'll leave you with that
Torsten
